apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: flux-system
spec:
  suspend: false
  chart:
    spec:
      chart: ./k8s/charts/servarr
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
      version: 0.1.1
  interval: 30m
  releaseName: bazarr
  targetNamespace: arr
  values:
    app:
      name: bazarr
      port: 6767
      image: lscr.io/linuxserver/bazarr@sha256:d24bd0048c759a468970989e9df11a6b96a7628d556d00f923e60a35ba59237b
    database:
      environment: true
      mainDatabase: bazarr
    legacyConfig:
      format: yaml
      path: /mnt/Data/legacy/servarr-seeds/bazarr
    exporter:
      enabled: true
      port: 9708
      image: ghcr.io/onedr0p/exportarr:v2.3.0@sha256:af535d94061cf97a52e1661945ffba78c03f9443eae7c0da1a80a5a4be56b520
