apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  suspend: false
  chart:
    spec:
      chart: ./k8s/charts/servarr
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
      version: 0.1.1
  interval: 30m
  releaseName: prowlarr
  targetNamespace: arr
  values:
    app:
      name: prowlarr
      port: 9696
      image: lscr.io/linuxserver/prowlarr@sha256:aaa16ba7d66e413db6d0358d3b6c68d833578ba7f176f24a51807181e7637fce
    database:
      logDatabase: prowlarr_log
      mainDatabase: prowlarr_main
    legacyConfig:
      path: /var/lib/private/prowlarr
    exporter:
      enabled: true
      port: 9710
      image: ghcr.io/onedr0p/exportarr:v2.3.0@sha256:af535d94061cf97a52e1661945ffba78c03f9443eae7c0da1a80a5a4be56b520
