apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: flux-system
spec:
  suspend: false
  chart:
    spec:
      chart: ./k8s/charts/servarr
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
      version: 0.1.1
  interval: 30m
  releaseName: sonarr
  targetNamespace: arr
  values:
    app:
      name: sonarr
      port: 8989
      image: lscr.io/linuxserver/sonarr@sha256:a5c1a5fecbef946927ab90ad68df319ac5fe644057e5fc18cd993f01ac07b2b2
    database:
      logDatabase: sonarr_log
      mainDatabase: sonarr_main
    legacyConfig:
      path: /mnt/Data/legacy/servarr-seeds/sonarr
    exporter:
      enabled: true
      port: 9712
      image: ghcr.io/onedr0p/exportarr:v2.3.0@sha256:af535d94061cf97a52e1661945ffba78c03f9443eae7c0da1a80a5a4be56b520
