apiVersion: v1
kind: Secret
metadata:
  name: immich-monitor
  namespace: immich
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:Njp6ZuT/9b4r/JZSiwCOvClLay2o7Nim7ghdkQ4yqsJrpdGyxzAMKzq39Ahxrw5t,iv:4qS45htVce/O/Z0eBVhhn/EVgZQh5+YeHZtk+v7WWyQ=,tag:BRdBI5AGkcHpLgEWYz+Pxg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZ1JMSkwxdmVTVTRjS1Ft
        QkRvZTdINk9KVmx3dzVLS0xnSW1HWG9WakhNCmVPUE1RbWVCSTFMdzl6Sy9GRG8r
        UjB2bjZJWk9oS1dPRE9aMG90a1FaclkKLS0tIHh3ZTB3ZTJBRWZ3TXdpY1VnYnJZ
        VjhrQlZOYW51NWtUbE10RGFQbmgwczAKtqaOpj8SmJKLpJXnpWIdekzjThr3/CiH
        E8SCt4HdGICh71E/TBsddkxr5P3eL1CCQYSZt5xXRfI6gphrKB/roQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQzlOUXNDUW15UlRiUzk2
        MDRkb3UyQWVnaWhyc0hXSHZ2ZlBnUDFONFFVClJnd2ttSnVsckZiUytUVS9OenJi
        UWsrekp4MCswYThMeWpBYy9FTnpVN0UKLS0tIDNPL0QyTGZIYkhwbHFZUmphN04z
        UEdna0UzRVNKRi9TS0dwU3J5WThEYk0KQcUtxp/ylR6SyENxydtprX4U2Lh54tZ6
        ulIoR691QbEW7+kwp6UsC8Q3DU9v0sLcxgkCZXB3cTBzlx9VQjonZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTUpVMUs3SkpjdHVsOWlV
        VmdnVUVFWlNmNGt3Qkk0Si9WOGxsUUVLenc0Ck5oK2xUNzdnc1RGb2ZLbWpnQlRr
        MnlrWUhqS0ZnSzV0cVNXR21RUmltVDAKLS0tIDdZemY4MitrM3JqYjBFbUh6Rm1Q
        V3djQ0RjZ0VrTitUZnc4QTdiRStEc3MKK/RQ4zrAAv7/D4jslmCi00cnGsPYh/+F
        2g5RTVhswwcwdpduIZwDfORUENVcedDR8+qveVF6Td51qXZ6jzSUdg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRno4YnFLY2R3TUZpSy95
        R2xBeEFmY3VOVUdHQXgwYXd4ZCtQd1pkYVVVCmY5UzR4bEtKOEFoQUZhUTFoMm9H
        MnhtaXptb2JHRTZKZU9jdzdjQ01jaVUKLS0tIGZlcnhLS2RiR3JoTHBMUG5XT3lN
        aU1hWG9xT0N6VGVaR3oxOXI2L2VuMUkKfHzn/fX6Qgxei3mB0hRGnBU9A3kuh2NN
        KU6fURobnoicJZrdXqHrZDLF9dNiylGHzJTv5jkzejcKMxaBHZNP7g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZnFjN2pkNk1Vc2tYMnVO
        SDVpS2FZVjJGN3UzOCtCODkwRkE5WmFVTGtNCm5mNmZrVkZ0Q09YK244QVlObWZ1
        NkVaZHJhVm5hc202MWEzaktPUTBWRTQKLS0tIHRBbEhoemhSenNITXRCTUxwaktz
        cnR3ckFXOGJPZ2RjdkJaMXdZTUVOYlkKko3jq+zAQUnYzw+PrT0NsMPSUFLomGr9
        CO4jVM5+YzmkkJDctW/lNKbPmslBPpq8CThnr7niR5J9cwjlEMywMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUeG0rN0U1OVB6dlBkSlZ6
        RGVvUVFLSnZIQmN1RlZSaW1sdm85U1R3RFhZClhyR3hTVkYxaDYxbDlsc1pXcVBO
        bGxLRm9rNXFWdi9CU0VMQkludkt3aDgKLS0tIFFCbEhvcnUrcHZNRUpyQjFDTEFo
        MzBCbjRIR0lSVDJtb3FYWk5GdnVLdlEKAHFAFqt9EsCEu3ksmY5xfvyW/csPAvcm
        a8+Z4ez7K7RgLhf4m708pU0qQDy5cCE/LwcXX/QEhWCJ4Uo2AWD5sQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZelpKQkVUeGlkWnpUb1Rk
        TXJSbkJlcXROTVZWMUM3cDNhQUJRUnRiMVhBCkE2RFg4dVNQYTNIS0V2UXgxLzYr
        VTg0cmdDZHdGTnZlaFZvNG5yaVA5UEUKLS0tIGtDeDIxVEdvS0lzMExEalhDTDEz
        ZnF5U1c4OUkwajJySTcrVE9tSG84VmMKOV2QQ2rFg/MwjBlPHUe/aczmbewSRdPT
        y8kTH3ShvKSxPFHAjDb049ALmJVpKsUiQSG7kYGXM72LEwyye26SVg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbGhRMlJMY2NhMXVNZG81
        eEFYdGdnOVRBeVRDUmt3RWN1c29pZTJTMm5vCllhMlU0Wml0d2t4ZkloU3JyQTM3
        UjRueFFVcm4zcXpGZ0hRMy9LUDUvU2MKLS0tIHliOHo1ZFB4Vkg2eklpdzJma1pO
        dkh4NXFlRWxwTnVvc24zZ0RKSi9GTGsKySruvne022yDU9FdewG362eO8yWOfE/J
        8k+13xDR8EymRgFvcdRKw95geqIOyRdcvc6f7broKwoe732Y+Ek5rA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcXEwaGxqN2V1TkxsaXJN
        d3pCemk0SlpiL0Z4Zy82cDgwTE1SZEhDeEg4CnVWN1E3eS9qRytYWDVEWnhRTnFR
        UWttNEpFR3haNTlwRmVCZXZnQlVnSTQKLS0tIFJnYlZ5SDRiUGFIKyttQS9qeWpR
        Z0pHRmJXZ0xTSmx1WGUyZ2c3a0pjZkEKKPoUW+Eo/r3jecqT89UJtUqQXY4YAO+4
        cWkJ97uI6Pav08brXZWABMmg16wHE727J1KpKvJd2kIcwQUimAzbIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T15:55:14Z"
  mac: ENC[AES256_GCM,data:1RAnTcy00GaCqNsYFkBBk3uOeTrY9KqCNbCYAUllV4Yuo8LRLeGKOH5qnv8PBOmuTdo9eykCKgK7wP2CPzG6Tq71XctDaAP8UX/tP8gvJja64GGx9r9yIdbgtgsK0XV4OSy7Yss7xUjTjD9iz2o+9kAbEqLj1AZao7yUZG6V9A0=,iv:roQ6fJmM98XZ099Shwei3PovUDN7lFvM40Ca7a4Y85w=,tag:WhDdEvm3YNcLxbUPgNG2rQ==,type:str]
  version: 3.13.3
