apiVersion: v1
kind: Secret
metadata:
  name: immich-monitor
  namespace: alloy-system
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:SdPFdtSK4Gox/QfK8ZkCNhfaqe4A28w2jN6uZ4PqCCyWwHWvANoNR+MrA+q5jxLM,iv:gkpdcYq3ygfUG3DjCgs9+mAAJYj5oo3X62bEL+wif9E=,tag:GrQPstdPVD3QlleVon/3pw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUVU0eXBudjB2TG11amcr
        STNXSzc3RTNWZmI4cE0wQ2ZtWjB0UEVOMmxjCjRsSUxsZ0lQb09XcHBRTytrME9s
        dFAraDNtWTRMWlJESGRSTnlsOEE2TFUKLS0tIHgxOXhnc09iMktkTzlrM2J2eWhR
        bXRhQzdQaHgxdVIranpoYW1maXEwSTAKV92T6Z8p8MBF0uKaymJmHcxvZOwmuoxr
        2zBnFMoJW4U9CxfD3lQ1NVRwSTk33TM1ZhM6yPNcjSjeO311sj+c8w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZVBHbzU1bWhOWmh3a3FX
        WXV2OGs1dW1LVTFST25xM2tRVk5XNG1sN0M0ClAva0k3OHFYRHhOcDBvbXNTRHph
        SjhnRHYvVDNLZDY3bUhrWEVzRkRyRk0KLS0tIDFKR0hrZW9DT1BKZzgyeGJZMkVx
        TDRCMXlEdVN5dUJPbjJLM2NTbG0xVTgKGAg0Bna3FDbNK+Gh0ez1OZ5/+wf4R4QY
        GT1sCT6S1BPsAsFmxUwlU1GzzO4LOKg3KOMTW4K3msg7ICKajPl3fA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuYWFVRTdyb2RYRWZCdnIy
        R2QxQXcvWEczUXkzNFY1Z0lwVHZMTDFYaVJjCjNMRlhLbVh6NDVXYWpMdHFtY0da
        YlV6VmJ3UU5KeFE1TlUwTExOT1B2a2sKLS0tIEdhdEY5MngzU3pOMTk2b0VWclRH
        WGZUOFIva2xVREg3R3o5M1dCMnVJdlEKhfMOzIS+MClEu4XQOeYNlsRIKhMvI9V8
        4NTVYBT8ipm4KAsemCIDz9nTf97xWDmLJeZUq3819WI3FRmLxWz6Gw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwa1BQaXpCRW1JWktNaUJo
        cXc5UWhoaE4vRitKRENNa2xlOWwyT3ZBd240CjdPeUpJb2VPcmlXSWhMUkkwV3VG
        OFVWdEJHb2h5dU1JdVlKc1VLZ3orL3cKLS0tIEdsaldBbExQUitGVGE5VmFZd3NN
        Rmo3cU9QUTVNako4OXUwN3VsSE9tMncKNySWm11H6W54/6PEkJkhNioejiAsBIQF
        mH88HvljaG3Flr0bF4xZ4EB1ue2STt+YyIJllSb6Ju+uG6RXz6HF0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORGFGck9WZlU2dG5SZ0Yr
        RCtwYStqa3pEdzBBQ2pEb3BicVpDVTEzT2o0Cnk2dXg0YkxKNlgvdDZCSjZpZ2pP
        TTFIeStZdzhqWUViTU9JN1F4K0lwWXcKLS0tIFE0L0dzd0J4cHBUQzRFM1RoMlNJ
        WVRkeVJsQlRLVEprMjQxWmVSVHJsSW8Kt3pvn31+RiycdBPnPQibVCmubCqDuWGz
        bE/8qm171IFPUdijRJB3ShcPQUoQ/gurwmajD57AUXd+n5dfpBRQlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTlRlbW5mY0M1UTNPVFcx
        OVRCM0tRekdQM3J3NHpMdkJ2bVVhMVZUdnpBCkY4WHgxcGtCR3ZVNTNkWGx2Mjhm
        N0pza3MvUDhsbGo2VFo4Ym5tSGVWcVUKLS0tIFRhb2grUHlVRUlOS0p5b0FpMUxq
        bGhBSHM4SE9yR0RqQmk5STJkTHV1WmcKDguIkHB09mKvtw1b/12Ux6ZoRuS/qkKd
        +oZomg/aMHYQ/SDU2CS21EwtmulNi6QtVU/DZJCPvhUdlpLZAa8k2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdTd2Smk1N1grYjM2b0NJ
        UXN1aC9KNnNyTm04T1BxNkRtMnZ2KzVBQkdjCmdKZkFzaUlFTEZOR05pVGFBbXo3
        enMvbm9xUXFpL2FaVDdsaGZRS3ZUUlkKLS0tIHV1ZWVMNTlSY1FTOHQwMXhxUjhK
        RnkyMTVpQ2lBTElNRkg4V0NWeHJkeTQK1p3eHZIpBF/spcFJXD1vfSMot8yetqv8
        fnCs2ioYS3OfqehDXyfMjDp9TOVJLQTsDvWP2PsEVlXpIXj/bNSJgQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTalBVMEFWZDlnNHE1WFJK
        ZklKMGhUdktmVkhiNXVJdmdrZlJTL2ljQ0JZCmI5OS9hTWJRYk1Ealh5VWpUQURG
        NWZGcm1zYVZPTHRFVStKL3FMeFdzQUkKLS0tIDJ1aWVmZTMyQzkyU0trOFltNG5R
        b0w0cWNES3E4ZWw4OXo1VnFySlBlTWcK5C4HO2CqaEmQZ1Qx6CNqcHYMnGC/eVD2
        WNn91NBJHmKf7iwzSIJpnTjPJYF65z/PO6H1uvfeq4LphkjOWltHYw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTGdkbmtyUGVjQjhFOFh1
        eEFpMSsrbktiRkZUSGg1ZmNhTGM0cVFCTjFJCno2MHVzTmN4blprZnVmUHEzU3NQ
        TGpIQVZKSTdHT0VJOXYxQnVvWU1VMGMKLS0tIEtaYW01L2NDdE0ybGtnV0t0VENv
        aDFuNXRxbnVxVGY5akplVzlWdS9Qa1EK/m55pBiQdG60H1SJE7CbIiu7YCXiXBo7
        ckbRzvm/uepSoafLJF+OpGDQ+3SMs2e4wJ2d8PltOFDPIxww/Ds26g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T15:55:14Z"
  mac: ENC[AES256_GCM,data:AkSG1/Ei6xZncet1VsL14jxZVmDLl0TM6E1p3v0LfZ1OwCuqBmLTMjvy/LmlmWqW3hLUDzd6RmjQX/0ZKwFAseMQk6Yo1INlVoxzeU78cBaI2IJ3XThWSIbpFk5G+CS7HPycE1AkscAGUESJOiJzpcoWDjUYmv/SkSDM8alxt9k=,iv:jLFMSjCW40VsJlZgSx7v8tt/eLvhJwoNFQHwaOLBUuE=,tag:KJLqAkMLmZ+o4yBLiBWc2g==,type:str]
  version: 3.13.3
