apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arr-namespace.yaml
  - forgejo-env.sops.yaml
  - forgejo-namespace.yaml
  - happyview-env.sops.yaml
  - happyview-namespace.sops.yaml
  - happyview-pg-creds.sops.yaml
  - immich-config.sops.yaml
  - immich-env.sops.yaml
  - immich-namespace.yaml
  - ombi-namespace.yaml
  - ombi-pg-creds.sops.yaml
  - ombi-database-configuration.sops.yaml
  - pocket-id-namespace.yaml
  - pocket-id-env.sops.yaml
  - pocket-id-pg-creds.sops.yaml
  - pinepods-namespace.yaml
  - pinepods-env.sops.yaml
  - pinepods-pg-creds.sops.yaml
  - nextcloud-env.sops.yaml
  - nextcloud-postgres.sops.yaml
  - paperless-env.sops.yaml
  - paperless-postgres.sops.yaml
  - pg-shared-app-arr.sops.yaml
  - pg-shared-app-cnpg.sops.yaml
  - pg-shared-b2.sops.yaml
  - tailscale-operator-values.sops.yaml
  - alloy-namespace.yaml
  - immich-monitor-immich.sops.yaml
  - immich-monitor-alloy-system.sops.yaml
