apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - immich.yaml
  - nextcloud.yaml
  - paperless.yaml
  - plex.yaml
  - uptime-kuma.yaml
  - watsup.yaml
  - ombi.yaml
  - pocket-id.yaml
  - happyview.yaml
