apiVersion: apps/v1
kind: Deployment
metadata:
  name: happyview
  namespace: happyview
  labels:
    app: happyview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: happyview
  template:
    metadata:
      labels:
        app: happyview
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: happyview
          image: ghcr.io/gamesgamesgamesgamesgames/happyview:2.15.0@sha256:8d67907eec075dad54a2f9f7374b65848788adf84e1de139cfaffc92513ef9db
          envFrom:
            - secretRef:
                name: happyview-env
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: happyview
  namespace: happyview
spec:
  selector:
    app: happyview
  ports:
    - name: http
      port: 80
      targetPort: http
