apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres
  namespace: flux-system
spec:
  dependsOn:
    - name: postgres-backups
    - name: secrets
  # Includes the Alloy-only metrics ingress policy.
  interval: 10m
  path: ./k8s/postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
  wait: true
