apiVersion: v1
kind: Namespace
metadata:
  name: audiobookshelf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      nodeSelector:
        johto.narwhal-snapper-ts.net/workload: media
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.36.1@sha256:3528a93b6442ffe54bd46771bbbab7c97084e1101071586d9dc2254f30bb4358
          env:
            - name: TZ
              value: America/New_York
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /healthcheck
              port: http
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /config
            - name: metadata
              mountPath: /metadata
            - name: media
              mountPath: /audiobooks/media
              readOnly: true
            - name: backblaze
              mountPath: /audiobooks/backblaze
              readOnly: true
      volumes:
        - name: config
          hostPath:
            path: /mnt/Data/apps/audiobookshelf/config
            type: DirectoryOrCreate
        - name: metadata
          hostPath:
            path: /mnt/Data/apps/audiobookshelf/metadata
            type: DirectoryOrCreate
        - name: media
          hostPath:
            path: /mnt/Media/Audiobooks
            type: Directory
        - name: backblaze
          hostPath:
            path: /mnt/Backblaze/Audiobooks
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  selector:
    app: audiobookshelf
  ports:
    - name: http
      port: 80
      targetPort: http
